### ISSUE TITLE
This benchmark is invalid

### ISSUE THREAD

**Issue by bluemonk3y** [databricks/benchmarks#5]
SEE https://data-artisans.com/blog/curious-case-broken-benchmark-revisiting-apache-flink-vs-databricks-runtime

More specifically:
All sounds fair, at least for Flink and Spark. We will note that the fact that Spark and Flink use in-memory data generation and KStreams goes through Kafka is itself a bias against KStreams.

**Comment by marmbrus** [comment]
Thanks for the feedback. This benchmark is actually [based on one originally proposed by data artisans](https://data-artisans.com/blog/extending-the-yahoo-streaming-benchmark) and we've corrected the inefficiencies reported in the blog you mentioned.

I agree that streaming engines that must commit every tuple to a durable, possibly replicated log are at a disadvantage. However, I don't think that means the benchmark is "invalid" as it can still be useful for measuring processing speed in engines that can decouple compute and storage.  That said, if there are any misconfigurations please do let us know so that we can correct them.
